version: '3'
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:9.6.20
    volumes:
      - ./tmp/db/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password

